package com.model;

import java.util.Date;

/**
 * TYuangong generated by MyEclipse Persistence Tools
 */

public class TYuangong implements java.io.Serializable
{

	// Fields

	private Integer yuangongId;
	private int yuangongOrgId;
	private String yuangongName;
	private String yuangongSex;

	private int yuangongAge;
	private String yuangongXueli;
	private String yuangongZhiwei;
	private String yuangongAddress;

	private String yuangongTel;
	private String yuangongEmail;
	private String yuangongGonghao;
	private String yuangongMima;
	
	private String yuangongDel;
	
	private TOrganization organization;
	
	public Integer getYuangongId()
	{
		return yuangongId;
	}
	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}
	public int getYuangongOrgId()
	{
		return yuangongOrgId;
	}
	public void setYuangongOrgId(int yuangongOrgId)
	{
		this.yuangongOrgId = yuangongOrgId;
	}
	public String getYuangongName()
	{
		return yuangongName;
	}
	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}
	
	public TOrganization getOrganization()
	{
		return organization;
	}
	public void setOrganization(TOrganization organization)
	{
		this.organization = organization;
	}
	
	public String getYuangongGonghao()
	{
		return yuangongGonghao;
	}
	public void setYuangongGonghao(String yuangongGonghao)
	{
		this.yuangongGonghao = yuangongGonghao;
	}
	public String getYuangongMima()
	{
		return yuangongMima;
	}
	public void setYuangongMima(String yuangongMima)
	{
		this.yuangongMima = yuangongMima;
	}
	public String getYuangongDel()
	{
		return yuangongDel;
	}
	public void setYuangongDel(String yuangongDel)
	{
		this.yuangongDel = yuangongDel;
	}
	public String getYuangongSex()
	{
		return yuangongSex;
	}
	public void setYuangongSex(String yuangongSex)
	{
		this.yuangongSex = yuangongSex;
	}
	public int getYuangongAge()
	{
		return yuangongAge;
	}
	public void setYuangongAge(int yuangongAge)
	{
		this.yuangongAge = yuangongAge;
	}
	public String getYuangongXueli()
	{
		return yuangongXueli;
	}
	public void setYuangongXueli(String yuangongXueli)
	{
		this.yuangongXueli = yuangongXueli;
	}
	public String getYuangongZhiwei()
	{
		return yuangongZhiwei;
	}
	public void setYuangongZhiwei(String yuangongZhiwei)
	{
		this.yuangongZhiwei = yuangongZhiwei;
	}
	public String getYuangongAddress()
	{
		return yuangongAddress;
	}
	public void setYuangongAddress(String yuangongAddress)
	{
		this.yuangongAddress = yuangongAddress;
	}
	public String getYuangongTel()
	{
		return yuangongTel;
	}
	public void setYuangongTel(String yuangongTel)
	{
		this.yuangongTel = yuangongTel;
	}
	public String getYuangongEmail()
	{
		return yuangongEmail;
	}
	public void setYuangongEmail(String yuangongEmail)
	{
		this.yuangongEmail = yuangongEmail;
	}

}